services:
  # Worker 0 (Master)
  ml-worker-0:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ml-worker-0
    network_mode: host
    environment:
      - MASTER_ADDR=localhost
      - MASTER_PORT=12355
      - WORLD_SIZE=4
      - RANK=0
      - LOCAL_RANK=0
      - SLURM_PROCID=0
      - SLURM_LOCALID=0
      - SLURM_NTASKS=4
      - SLURM_NODEID=0
      - SLURM_JOB_ID=docker-job-001
      - SLURM_JOB_NAME=ml_training_demo
      - SLURM_JOB_NODELIST=ml-worker-0,ml-worker-1,ml-worker-2,ml-worker-3
    volumes:
      - ./data:/app/data
      - ./checkpoints:/app/checkpoints
      - ./logs:/app/logs
    command: ["python3", "slurm_training_demo.py", "--config", "config.json"]

  # Worker 1
  ml-worker-1:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ml-worker-1
    network_mode: host
    environment:
      - MASTER_ADDR=localhost
      - MASTER_PORT=12355
      - WORLD_SIZE=4
      - RANK=1
      - LOCAL_RANK=0
      - SLURM_PROCID=1
      - SLURM_LOCALID=0
      - SLURM_NTASKS=4
      - SLURM_NODEID=1
      - SLURM_JOB_ID=docker-job-001
      - SLURM_JOB_NAME=ml_training_demo
      - SLURM_JOB_NODELIST=ml-worker-0,ml-worker-1,ml-worker-2,ml-worker-3
    volumes:
      - ./data:/app/data
      - ./checkpoints:/app/checkpoints
      - ./logs:/app/logs
    command: ["sh", "-c", "sleep 5 && python3 slurm_training_demo.py --config config.json"]

  # Worker 2
  ml-worker-2:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ml-worker-2
    network_mode: host
    environment:
      - MASTER_ADDR=localhost
      - MASTER_PORT=12355
      - WORLD_SIZE=4
      - RANK=2
      - LOCAL_RANK=0
      - SLURM_PROCID=2
      - SLURM_LOCALID=0
      - SLURM_NTASKS=4
      - SLURM_NODEID=2
      - SLURM_JOB_ID=docker-job-001
      - SLURM_JOB_NAME=ml_training_demo
      - SLURM_JOB_NODELIST=ml-worker-0,ml-worker-1,ml-worker-2,ml-worker-3
    volumes:
      - ./data:/app/data
      - ./checkpoints:/app/checkpoints
      - ./logs:/app/logs
    command: ["sh", "-c", "sleep 5 && python3 slurm_training_demo.py --config config.json"]

  # Worker 3
  ml-worker-3:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ml-worker-3
    network_mode: host
    environment:
      - MASTER_ADDR=localhost
      - MASTER_PORT=12355
      - WORLD_SIZE=4
      - RANK=3
      - LOCAL_RANK=0
      - SLURM_PROCID=3
      - SLURM_LOCALID=0
      - SLURM_NTASKS=4
      - SLURM_NODEID=3
      - SLURM_JOB_ID=docker-job-001
      - SLURM_JOB_NAME=ml_training_demo
      - SLURM_JOB_NODELIST=ml-worker-0,ml-worker-1,ml-worker-2,ml-worker-3
    volumes:
      - ./data:/app/data
      - ./checkpoints:/app/checkpoints
      - ./logs:/app/logs
    command: ["sh", "-c", "sleep 5 && python3 slurm_training_demo.py --config config.json"]

